// Comprehensive website database for NESA Search Engine
const websiteDatabase = [
    // NESA Products
    {title: "Polyblocks - Official Game", url: "https://polyblocks.onrender.com", snippet: "Polyblocks is a 3D block-building game with multiple game modes including Playground, Battle, Parkour, and Anarchy. Download Pre-test 0.5 now!"},
    {title: "NESA Explorer - Web Browser", url: "https://polyblocks.onrender.com/explorer", snippet: "NESA Explorer is the official web browser for NESA 95. Experience the web with cutting-edge technology from 1995."},
    {title: "NESA 95 - Home", url: "https://polyblocks.onrender.com/home", snippet: "Welcome to NESA 95, your gateway to the digital world. Latest news, updates, and downloads for all NESA products."},
    {title: "Polyblocks Download Center", url: "https://polyblocks.onrender.com/download", snippet: "Download the latest version of Polyblocks Pre-test 0.5. Features include multiplayer support, new game modes, and improved graphics."},
    {title: "NESA Search Engine Documentation", url: "https://polyblocks.onrender.com/docs", snippet: "Learn how to use NESA Search Engine (ASBAN) to find content across the NESA platform. Advanced search tips and tricks included."},
    
    // Search Engines
    {title: "Google - Search Engine", url: "https://www.google.com", snippet: "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for."},
    {title: "Bing - Microsoft Search", url: "https://www.bing.com", snippet: "Bing helps you turn information into action, making it faster and easier to go from searching to doing."},
    {title: "DuckDuckGo - Privacy Search", url: "https://duckduckgo.com", snippet: "The Internet privacy company that empowers you to seamlessly take control of your personal information online, without any tradeoffs."},
    {title: "Yahoo - Search and News", url: "https://www.yahoo.com", snippet: "Yahoo makes it easy to enjoy what matters most in your world. Best in class Yahoo Mail, breaking local, national and global news, finance, sports, music."},
    {title: "Yandex - Russian Search", url: "https://www.yandex.com", snippet: "Yandex is a technology company that builds intelligent products and services powered by machine learning."},
    {title: "Baidu - Chinese Search", url: "https://www.baidu.com", snippet: "Baidu is the leading Chinese language search engine, providing simple and reliable search experiences to hundreds of millions of users."},
    
    // Social Media
    {title: "YouTube - Videos, Music and Live Streams", url: "https://www.youtube.com", snippet: "Enjoy the videos and music you love, upload original content, and share it all with friends, family, and the world on YouTube."},
    {title: "Facebook - Social Network", url: "https://www.facebook.com", snippet: "Connect with friends, family and other people you know. Share photos and videos, send messages and get updates."},
    {title: "Instagram - Photo Sharing", url: "https://www.instagram.com", snippet: "Create an account or log in to Instagram - A simple, fun & creative way to capture, edit & share photos, videos & messages with friends & family."},
    {title: "Twitter - Social Media Platform", url: "https://twitter.com", snippet: "From breaking news and entertainment to sports and politics, get the full story with all the live commentary on Twitter."},
    {title: "TikTok - Short Videos", url: "https://www.tiktok.com", snippet: "TikTok is THE destination for mobile videos. On TikTok, short-form videos are exciting, spontaneous, and genuine."},
    {title: "LinkedIn - Professional Network", url: "https://www.linkedin.com", snippet: "LinkedIn is the world's largest professional network with over 800 million members. Find connections, leads, and new opportunities."},
    {title: "Reddit - Dive into anything", url: "https://www.reddit.com", snippet: "Reddit is a network of communities where people can dive into their interests, hobbies and passions. There's a community for whatever you're interested in."},
    {title: "Pinterest - Visual Discovery", url: "https://www.pinterest.com", snippet: "Discover recipes, home ideas, style inspiration and other ideas to try on Pinterest."},
    {title: "Snapchat - Camera Company", url: "https://www.snapchat.com", snippet: "Snapchat is a camera and messaging app that connects people to their friends and the world."},
    {title: "Discord - Chat for Communities", url: "https://discord.com", snippet: "Discord is the easiest way to talk over voice, video, and text. Talk, chat, hang out, and stay close with your friends and communities."},
    {title: "Telegram - Messaging App", url: "https://telegram.org", snippet: "Telegram is a cloud-based mobile and desktop messaging app with a focus on security and speed."},
    {title: "WhatsApp - Messaging", url: "https://www.whatsapp.com", snippet: "WhatsApp Messenger: More than 2 billion people in over 180 countries use WhatsApp to stay in touch with friends and family, anytime and anywhere."},
    
    // News & Media
    {title: "CNN - Breaking News", url: "https://www.cnn.com", snippet: "View the latest news and breaking news today for U.S., world, weather, entertainment, politics and health at CNN.com."},
    {title: "BBC News - World News", url: "https://www.bbc.com/news", snippet: "Visit BBC News for up-to-the-minute news, breaking news, video, audio and feature stories from around the world."},
    {title: "The New York Times", url: "https://www.nytimes.com", snippet: "The New York Times: Find breaking news, multimedia, reviews & opinion on Washington, business, sports, movies, travel, books, jobs, education, real estate."},
    {title: "Reuters - Business News", url: "https://www.reuters.com", snippet: "Reuters.com brings you the latest news from around the world, covering breaking news in markets, business, politics, entertainment, technology, video and pictures."},
    {title: "The Guardian - News", url: "https://www.theguardian.com", snippet: "Latest news, sport, business, comment, analysis and reviews from the Guardian, the world's leading liberal voice."},
    {title: "Al Jazeera - International News", url: "https://www.aljazeera.com", snippet: "News, analysis from the Middle East and worldwide, multimedia and interactives, opinions, documentaries, podcasts, long reads and broadcast schedule."},
    
    // Entertainment & Streaming
    {title: "Netflix - Watch TV Shows Online", url: "https://www.netflix.com", snippet: "Watch Netflix movies & TV shows online or stream right to your smart TV, game console, PC, Mac, mobile, tablet and more."},
    {title: "Hulu - Stream TV and Movies", url: "https://www.hulu.com", snippet: "Watch thousands of shows and movies, with plans starting at $7.99/month. Stream TV episodes of South Park, Empire, SNL, Modern Family and popular movies."},
    {title: "Disney+ - Streaming Service", url: "https://www.disneyplus.com", snippet: "Stream Disney, Pixar, Marvel, Star Wars, National Geographic and more. All together for the first time ever."},
    {title: "HBO Max - Premium Streaming", url: "https://www.hbomax.com", snippet: "Stream all of HBO together with even more from Warner Bros., DC, Studio Ghibli, Cartoon Network and more."},
    {title: "Twitch - Live Streaming Platform", url: "https://www.twitch.tv", snippet: "Twitch is the world's leading video platform and community for gamers. Watch and chat now with millions of other fans from around the world."},
    {title: "Spotify - Music Streaming", url: "https://www.spotify.com", snippet: "Spotify is a digital music service that gives you access to millions of songs, podcasts and videos from artists all over the world."},
    {title: "Apple Music - Music Service", url: "https://www.apple.com/apple-music", snippet: "Apple Music is a streaming service that allows you to listen to over 90 million songs. Its great features include the ability to download your favorite tracks."},
    {title: "SoundCloud - Music Platform", url: "https://soundcloud.com", snippet: "Discover and play over 265 million music tracks. Join the world's largest online community of artists, bands, podcasters and creators of music & audio."},
    {title: "IMDb - Movies, TV and Celebrities", url: "https://www.imdb.com", snippet: "IMDb is the world's most popular and authoritative source for movie, TV and celebrity content. Find ratings and reviews for the newest movie and TV shows."},
    
    // Gaming
    {title: "Steam - Gaming Platform", url: "https://store.steampowered.com", snippet: "Steam is the ultimate destination for playing, discussing, and creating games. Browse thousands of games and discover your next favorite."},
    {title: "Epic Games Store", url: "https://www.epicgames.com", snippet: "Download and play PC Games of every genre. We have mods, DLC and Free Games too! Games for everyone."},
    {title: "Xbox - Gaming Console", url: "https://www.xbox.com", snippet: "Experience the new generation of games and entertainment with Xbox. Explore consoles, new and old Xbox games and accessories."},
    {title: "PlayStation - Gaming", url: "https://www.playstation.com", snippet: "The official PlayStation website - explore PlayStation®5, PlayStation®4, PlayStation VR, and the latest games and accessories."},
    {title: "Nintendo - Gaming Company", url: "https://www.nintendo.com", snippet: "Discover Nintendo Switch, the video game system you can play at home or on the go. Plus, get the latest Nintendo news and learn about games."},
    {title: "Roblox - Gaming Platform", url: "https://www.roblox.com", snippet: "Roblox is the ultimate virtual universe that lets you create, share experiences with friends, and be anything you can imagine."},
    {title: "Minecraft - Video Game", url: "https://www.minecraft.net", snippet: "Explore new gaming adventures, accessories, & merchandise on the Minecraft Official Site. Buy & download the game here, or check the site for the latest news."},
    {title: "Fortnite - Battle Royale", url: "https://www.fortnite.com", snippet: "Fortnite is the completely free multiplayer game where you and your friends can jump into Battle Royale or Fortnite Creative."},
    {title: "League of Legends", url: "https://www.leagueoflegends.com", snippet: "League of Legends is a team-based game with over 140 champions to make epic plays with."},
    {title: "IGN - Gaming News", url: "https://www.ign.com", snippet: "IGN is your #1 destination for all video game news, reviews, guides, walkthroughs, and more."},
    
    // Shopping & E-commerce
    {title: "Amazon - Online Shopping", url: "https://www.amazon.com", snippet: "Free shipping on millions of items. Get the best of Shopping and Entertainment with Prime. Enjoy low prices and great deals on the largest selection."},
    {title: "eBay - Online Marketplace", url: "https://www.ebay.com", snippet: "Buy & sell electronics, cars, clothes, collectibles & more on eBay, the world's online marketplace."},
    {title: "Walmart - Save Money Live Better", url: "https://www.walmart.com", snippet: "Shop for Every Day Low Prices. Free Shipping on Orders $35+ or Pickup In-Store and get a Pickup Discount."},
    {title: "Target - Online Store", url: "https://www.target.com", snippet: "Shop Target online and in-store for everything from groceries and essentials to clothing and electronics."},
    {title: "Best Buy - Electronics", url: "https://www.bestbuy.com", snippet: "Shop Best Buy for electronics, computers, appliances, cell phones, video games & more new tech."},
    {title: "AliExpress - Shopping", url: "https://www.aliexpress.com", snippet: "Online shopping for the latest electronics, fashion, phone accessories, computer electronics, toys and more."},
    {title: "Etsy - Handmade Goods", url: "https://www.etsy.com", snippet: "Shop for handmade, vintage, custom, and unique gifts for everyone on Etsy."},
    {title: "Newegg - Tech Shopping", url: "https://www.newegg.com", snippet: "Shop the latest computer parts, laptops, GPUs, motherboards, processors, power supplies, cases, and more."},
    
    // Education & Reference
    {title: "Wikipedia - The Free Encyclopedia", url: "https://www.wikipedia.org", snippet: "Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation."},
    {title: "Khan Academy - Free Education", url: "https://www.khanacademy.org", snippet: "Learn for free about math, art, computer programming, economics, physics, chemistry, biology, medicine, finance, history, and more."},
    {title: "Coursera - Online Courses", url: "https://www.coursera.org", snippet: "Learn online and earn valuable credentials from top universities like Yale, Michigan, Stanford, and leading companies like Google and IBM."},
    {title: "edX - Online Learning", url: "https://www.edx.org", snippet: "Access 2000 free online courses from 140 leading institutions worldwide. Gain new skills and earn a certificate of completion."},
    {title: "Udemy - Online Learning", url: "https://www.udemy.com", snippet: "Udemy is an online learning and teaching marketplace with over 183,000 courses and 40 million students."},
    {title: "Duolingo - Language Learning", url: "https://www.duolingo.com", snippet: "Learn a new language with the world's most-downloaded education app! Duolingo is the fun, free app for learning 35+ languages."},
    {title: "Quizlet - Study Tools", url: "https://quizlet.com", snippet: "Simple free learning tools for students and teachers. Create custom flashcards, study sets, and more to help you learn."},
    {title: "Wolfram Alpha - Computational", url: "https://www.wolframalpha.com", snippet: "Wolfram|Alpha brings expert-level knowledge and capabilities to the broadest possible range of people—spanning all professions and education levels."},
    
    // Development & Programming
    {title: "GitHub - Where the world builds software", url: "https://github.com", snippet: "GitHub is where over 100 million developers shape the future of software, together. Contribute to the open source community, manage your Git repositories."},
    {title: "Stack Overflow - Developer Community", url: "https://stackoverflow.com", snippet: "Stack Overflow is the largest, most trusted online community for developers to learn, share their programming knowledge, and build their careers."},
    {title: "GitLab - DevOps Platform", url: "https://gitlab.com", snippet: "GitLab is the open DevOps platform that brings everyone together to do better software faster."},
    {title: "Bitbucket - Git Solution", url: "https://bitbucket.org", snippet: "Bitbucket is more than just Git code management. Bitbucket gives teams one place to plan projects, collaborate on code, test, and deploy."},
    {title: "CodePen - Front-end Playground", url: "https://codepen.io", snippet: "CodePen is a social development environment for front-end designers and developers. Build and deploy a website, show off your work."},
    {title: "JSFiddle - Code Playground", url: "https://jsfiddle.net", snippet: "Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor."},
    {title: "MDN Web Docs - Resources for developers", url: "https://developer.mozilla.org", snippet: "The MDN Web Docs site provides information about Open Web technologies including HTML, CSS, and APIs for both Web sites and progressive web apps."},
    {title: "W3Schools - Web Development Tutorials", url: "https://www.w3schools.com", snippet: "W3Schools offers free online tutorials, references and exercises in all the major languages of the web. Covering popular subjects like HTML, CSS, JavaScript, Python, SQL, Java, and many more."},
    {title: "FreeCodeCamp - Learn to Code", url: "https://www.freecodecamp.org", snippet: "Learn to code — for free. Build projects. Earn certifications. Since 2014, more than 40,000 freeCodeCamp.org graduates have gotten jobs at tech companies."},
    {title: "Codecademy - Learn Coding", url: "https://www.codecademy.com", snippet: "Learn the technical skills to get the job you want. Join over 50 million people choosing Codecademy to start a new career."},
    {title: "LeetCode - Coding Practice", url: "https://leetcode.com", snippet: "LeetCode is the best platform to help you enhance your skills, expand your knowledge and prepare for technical interviews."},
    {title: "HackerRank - Coding Challenges", url: "https://www.hackerrank.com", snippet: "HackerRank is the market-leading technical assessment and remote interview solution for hiring developers."},
    {title: "npm - Package Manager", url: "https://www.npmjs.com", snippet: "npm is the world's largest software registry. Open source developers use npm to share software."},
    {title: "PyPI - Python Packages", url: "https://pypi.org", snippet: "The Python Package Index (PyPI) is a repository of software for the Python programming language."},
    
    // Design & Creative
    {title: "Adobe Creative Cloud", url: "https://www.adobe.com", snippet: "Adobe Creative Cloud gives you the world's best creative apps and services so you can make anything you can imagine."},
    {title: "Figma - Design Tool", url: "https://www.figma.com", snippet: "Figma connects everyone in the design process so teams can deliver better products, faster."},
    {title: "Canva - Graphic Design", url: "https://www.canva.com", snippet: "Canva is a free-to-use online graphic design tool. Use it to create social media posts, presentations, posters, videos, logos and more."},
    {title: "Dribbble - Design Community", url: "https://dribbble.com", snippet: "Dribbble is the leading destination to find & showcase creative work and home to the world's best design professionals."},
    {title: "Behance - Creative Portfolios", url: "https://www.behance.net", snippet: "Behance is the world's largest creative network for showcasing and discovering creative work."},
    {title: "Unsplash - Free Photos", url: "https://unsplash.com", snippet: "Beautiful, free images and photos that you can download and use for any project. Better than any royalty free or stock photos."},
    {title: "Pexels - Free Stock Photos", url: "https://www.pexels.com", snippet: "The best free stock photos, royalty free images & videos shared by creators."},
    {title: "Pixabay - Free Images", url: "https://pixabay.com", snippet: "Stunning free images & royalty free stock. Over 2.6 million+ high quality stock images, videos and music shared by our talented community."},
    
    // Cloud & Productivity
    {title: "Google Drive - Cloud Storage", url: "https://drive.google.com", snippet: "Access Google Drive with a free Google account (for personal use) or Google Workspace account (for business use)."},
    {title: "Dropbox - File Hosting", url: "https://www.dropbox.com", snippet: "Dropbox is a modern workspace designed to reduce busywork-so you can focus on the things that matter."},
    {title: "Microsoft OneDrive - Cloud Storage", url: "https://onedrive.live.com", snippet: "Store photos and docs online. Access them from any PC, Mac or phone. Create and work together on Word, Excel or PowerPoint documents."},
    {title: "Google Docs - Online Documents", url: "https://docs.google.com", snippet: "Create and edit text documents right in your browser—no special software required."},
    {title: "Notion - All-in-one Workspace", url: "https://www.notion.so", snippet: "Notion is the all-in-one workspace for your notes, tasks, wikis, and databases."},
    {title: "Trello - Project Management", url: "https://trello.com", snippet: "Trello helps teams move work forward. Collaborate, manage projects, and reach new productivity peaks."},
    {title: "Asana - Work Management", url: "https://asana.com", snippet: "Asana is the work management platform teams use to stay focused on the goals, projects, and daily tasks that grow business."},
    {title: "Slack - Team Communication", url: "https://slack.com", snippet: "Slack is where work flows. It's where the people you need, the information you share, and the tools you use come together to get things done."},
    {title: "Zoom - Video Conferencing", url: "https://zoom.us", snippet: "Zoom is the leader in modern enterprise video communications, with an easy, reliable cloud platform for video and audio conferencing."},
    {title: "Microsoft Teams - Collaboration", url: "https://www.microsoft.com/teams", snippet: "Make amazing things happen together at home, work, and school with Microsoft Teams."},
    
    // Travel & Maps
    {title: "Google Maps - Navigation", url: "https://www.google.com/maps", snippet: "Find local businesses, view maps and get driving directions in Google Maps."},
    {title: "Airbnb - Vacation Rentals", url: "https://www.airbnb.com", snippet: "Find vacation rentals, cabins, beach houses, unique homes and experiences around the world - all made possible by hosts on Airbnb."},
    {title: "Booking.com - Hotels", url: "https://www.booking.com", snippet: "Official site of Booking.com. Choose from over a million apartments, hotels, chalets, bed and breakfasts, hostels and more."},
    {title: "Expedia - Travel Booking", url: "https://www.expedia.com", snippet: "Book your next trip with Expedia. Save on cheap flights, hotels, vacation packages, and more. Earn airline miles and hotel points."},
    {title: "TripAdvisor - Travel Reviews", url: "https://www.tripadvisor.com", snippet: "Plan your next trip, read reviews and get travel advice from our community on where to stay and what to do."},
    {title: "Uber - Ride Sharing", url: "https://www.uber.com", snippet: "Uber is a platform where those who drive and deliver can connect with riders, eaters, and restaurants."},
    {title: "Lyft - Rideshare Service", url: "https://www.lyft.com", snippet: "Get a ride in minutes. Or become a driver and earn money on your schedule."},
    
    // Finance & Business
    {title: "PayPal - Online Payments", url: "https://www.paypal.com", snippet: "PayPal has remained at the forefront of the digital payment revolution for more than 20 years."},
    {title: "Venmo - Mobile Payments", url: "https://venmo.com", snippet: "Venmo is a digital wallet that makes money easier for everyone from students to small businesses."},
    {title: "Coinbase - Cryptocurrency", url: "https://www.coinbase.com", snippet: "Coinbase is a secure online platform for buying, selling, transferring, and storing cryptocurrency."},
    {title: "Bloomberg - Business News", url: "https://www.bloomberg.com", snippet: "Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News."},
    {title: "CNBC - Business News", url: "https://www.cnbc.com", snippet: "Get stock market quotes, personal finance advice, company news and more. CNBC is the world leader in business news and real-time financial market coverage."},
    {title: "Yahoo Finance - Stock Market", url: "https://finance.yahoo.com", snippet: "At Yahoo Finance, you get free stock quotes, up-to-date news, portfolio management resources, international market data, social interaction and mortgage rates."},
    {title: "Robinhood - Investing", url: "https://robinhood.com", snippet: "Robinhood has commission-free investing, and tools to help shape your financial future. Sign up and get your first stock free."},
    
    // Health & Fitness
    {title: "WebMD - Health Information", url: "https://www.webmd.com", snippet: "Better information. Better health. WebMD provides valuable health information, tools for managing your health, and support to those who seek information."},
    {title: "Mayo Clinic - Medical Center", url: "https://www.mayoclinic.org", snippet: "Mayo Clinic offers expert, whole-person care to everyone who needs healing."},
    {title: "Healthline - Medical Information", url: "https://www.healthline.com", snippet: "Healthline Media, Inc. is an American website and provider of health information headquartered in San Francisco, California."},
    {title: "MyFitnessPal - Fitness App", url: "https://www.myfitnesspal.com", snippet: "MyFitnessPal is the leading app for tracking—and conquering—your nutrition and fitness goals."},
    {title: "Fitbit - Fitness Tracking", url: "https://www.fitbit.com", snippet: "Find your fit with Fitbit's family of fitness products that help you stay motivated and improve your health by tracking your activity, exercise, food, weight and sleep."},
    
    // Technology & Gadgets
    {title: "The Verge - Technology News", url: "https://www.theverge.com", snippet: "The Verge was founded in 2011 in partnership with Vox Media, and covers the intersection of technology, science, art, and culture."},
    {title: "TechCrunch - Startup News", url: "https://techcrunch.com", snippet: "TechCrunch reporting on the business of technology, startups, venture capital funding, and Silicon Valley."},
    {title: "CNET - Tech News", url: "https://www.cnet.com", snippet: "CNET is the world's leader in tech product reviews, news, prices, videos, forums, how-tos and more."},
    {title: "Wired - Technology Magazine", url: "https://www.wired.com", snippet: "Wired is where tomorrow is realized. It is the essential source of information and ideas that make sense of a world in constant transformation."},
    {title: "Engadget - Electronics", url: "https://www.engadget.com", snippet: "Engadget is the original home for technology news and reviews. We cover a wide range of consumer electronics and smart gadgets."},
    {title: "Tom's Hardware - PC Components", url: "https://www.tomshardware.com", snippet: "Tom's Hardware helps you buy the best hardware and build the best PC. Get the latest PC hardware reviews, tech news and more."},
    {title: "AnandTech - Hardware Reviews", url: "https://www.anandtech.com", snippet: "AnandTech is a leading source of computer hardware news and reviews since 1997."},
    
    // Science & Research
    {title: "NASA - Space Exploration", url: "https://www.nasa.gov", snippet: "NASA explores the unknown in air and space, innovates for the benefit of humanity, and inspires the world through discovery."},
    {title: "Nature - Science Journal", url: "https://www.nature.com", snippet: "Nature is a British weekly scientific journal founded and based in London. It is one of the most recognizable scientific journals in the world."},
    {title: "Science Magazine", url: "https://www.sciencemag.org", snippet: "Science publishes the very best in research across the sciences, with articles that consistently rank among the most cited in the world."},
    {title: "Scientific American", url: "https://www.scientificamerican.com", snippet: "Scientific American is the essential guide to the most awe-inspiring advances in science and technology."},
    {title: "arXiv - Research Papers", url: "https://arxiv.org", snippet: "arXiv is a free distribution service and an open-access archive for scholarly articles in the fields of physics, mathematics, computer science, and more."},
    
    // Food & Cooking
    {title: "AllRecipes - Cooking Recipes", url: "https://www.allrecipes.com", snippet: "Find and share everyday cooking inspiration on Allrecipes. Discover recipes, cooks, videos, and how-tos based on the food you love."},
    {title: "Food Network - Cooking Shows", url: "https://www.foodnetwork.com", snippet: "Food Network is an American basic cable channel owned by Television Food Network. It focuses on food-related programming."},
    {title: "Tasty - Recipe Videos", url: "https://tasty.co", snippet: "Tasty is the world's largest social food network, reaching more than 500 million people around the globe with its signature fun, easy, and delicious videos."},
    {title: "Epicurious - Food Recipes", url: "https://www.epicurious.com", snippet: "Find quick & easy recipes, browse menus, and discover the perfect restaurant recipes with Epicurious."},
    {title: "Serious Eats - Food Science", url: "https://www.seriouseats.com", snippet: "Serious Eats provides recipes you want to make, in-depth technique and cooking articles, and science-backed explanations."},
    
    // Sports & Fitness
    {title: "ESPN - Sports Network", url: "https://www.espn.com", snippet: "Visit ESPN to get up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more."},
    {title: "NFL - Football League", url: "https://www.nfl.com", snippet: "The official source for NFL news, schedules, stats, scores and more."},
    {title: "NBA - Basketball", url: "https://www.nba.com", snippet: "The official site of the National Basketball Association. Follow the action on NBA scores, schedules, stats, news, Team and Player news."},
    {title: "MLB - Baseball", url: "https://www.mlb.com", snippet: "The official website of Major League Baseball with the most up-to-date information on scores, schedules, stats, tickets, and team news."},
    {title: "FIFA - Soccer/Football", url: "https://www.fifa.com", snippet: "The official FIFA website with all the latest news and featured stories from world football's governing body."},
    {title: "Olympics - Olympic Games", url: "https://www.olympics.com", snippet: "Official website of the Olympic Games. Find more about the Olympic Movement, Games, Athletes, Sports and Olympic Results."},
    
    // Government & Organizations
    {title: "United Nations - UN", url: "https://www.un.org", snippet: "The United Nations is an international organization founded in 1945 committed to maintaining international peace and security."},
    {title: "World Health Organization", url: "https://www.who.int", snippet: "WHO's primary role is to direct international health within the United Nations' system and to lead partners in global health responses."},
    {title: "CIA - Central Intelligence", url: "https://www.cia.gov", snippet: "The Central Intelligence Agency collects, evaluates and disseminates vital information on economic, military, political, scientific and other matters."},
    {title: "FBI - Federal Bureau", url: "https://www.fbi.gov", snippet: "The FBI is the domestic intelligence and security service of the United States and its principal federal law enforcement agency."},
    {title: "IRS - Tax Service", url: "https://www.irs.gov", snippet: "The official website of the Internal Revenue Service. Get info on filing, paying, and planning your taxes."},
    
    // Miscellaneous Popular Sites
    {title: "Quora - Q&A Platform", url: "https://www.quora.com", snippet: "Quora is a place to gain and share knowledge. It's a platform to ask questions and connect with people who contribute unique insights."},
    {title: "Medium - Publishing Platform", url: "https://medium.com", snippet: "Medium is an open platform where readers find dynamic thinking, and where expert and undiscovered voices can share their writing on any topic."},
    {title: "Tumblr - Microblogging", url: "https://www.tumblr.com", snippet: "Tumblr is a place to express yourself, discover yourself, and bond over the stuff you love."},
    {title: "DeviantArt - Art Community", url: "https://www.deviantart.com", snippet: "DeviantArt is the world's largest online social community for artists and art enthusiasts."},
    {title: "Imgur - Image Sharing", url: "https://imgur.com", snippet: "Discover the magic of the internet at Imgur, a community powered entertainment destination."},
    {title: "Giphy - GIF Database", url: "https://giphy.com", snippet: "GIPHY is your top source for the best & newest GIFs & Animated Stickers online."},
    {title: "Archive.org - Internet Archive", url: "https://archive.org", snippet: "Internet Archive is a non-profit library of millions of free books, movies, software, music, websites, and more."},
    {title: "Weather.com - Weather Forecast", url: "https://weather.com", snippet: "The Weather Channel and weather.com provide a national and local weather forecast for cities, as well as weather radar, report and hurricane coverage."},
    {title: "Craigslist - Classified Ads", url: "https://www.craigslist.org", snippet: "Craigslist provides local classifieds and forums for jobs, housing, for sale, services, local community, and events."},
    {title: "Indeed - Job Search", url: "https://www.indeed.com", snippet: "Indeed is the #1 job site in the world with over 250 million unique visitors every month."},
    {title: "Glassdoor - Job Reviews", url: "https://www.glassdoor.com", snippet: "Search millions of jobs and get the inside scoop on companies with employee reviews, personalized salary tools, and more."},
    {title: "Zillow - Real Estate", url: "https://www.zillow.com", snippet: "Zillow is an online real estate database company founded in 2006. Browse real estate listings and property information."},
    {title: "Yelp - Local Reviews", url: "https://www.yelp.com", snippet: "Yelp connects people with great local businesses. Read reviews, check out photos, and browse listings."},
    
    // Animals Theme
    {title: "Dog - Wikipedia", url: "https://en.wikipedia.org/wiki/Dog", snippet: "The dog is a domesticated descendant of the wolf. Dogs were the first species to be domesticated by hunter-gatherers."},
    {title: "Cat - Wikipedia", url: "https://en.wikipedia.org/wiki/Cat", snippet: "The cat is a domestic species of small carnivorous mammal. It is the only domesticated species in the family Felidae."},
    {title: "Lion - Wikipedia", url: "https://en.wikipedia.org/wiki/Lion", snippet: "The lion is a large cat of the genus Panthera native to Africa and India. It has a muscular, broad-chested body."},
    {title: "Tiger - Wikipedia", url: "https://en.wikipedia.org/wiki/Tiger", snippet: "The tiger is the largest living cat species and a member of the genus Panthera. It is most recognizable for its dark vertical stripes."},
    {title: "Elephant - Wikipedia", url: "https://en.wikipedia.org/wiki/Elephant", snippet: "Elephants are the largest existing land animals. Three living species are currently recognised: the African bush elephant, the African forest elephant, and the Asian elephant."},
    {title: "Bear - Wikipedia", url: "https://en.wikipedia.org/wiki/Bear", snippet: "Bears are carnivoran mammals of the family Ursidae. They are classified as caniforms, or doglike carnivorans."},
    {title: "Wolf - Wikipedia", url: "https://en.wikipedia.org/wiki/Wolf", snippet: "The wolf, also known as the gray wolf or grey wolf, is a large canine native to Eurasia and North America."},
    {title: "Horse - Wikipedia", url: "https://en.wikipedia.org/wiki/Horse", snippet: "The horse is a domesticated, one-toed, hoofed mammal. It belongs to the taxonomic family Equidae."},
    {title: "Rabbit - Wikipedia", url: "https://en.wikipedia.org/wiki/Rabbit", snippet: "Rabbits are small mammals in the family Leporidae. They are known for their long ears, large hind legs, and short fluffy tails."},
    {title: "Fox - Wikipedia", url: "https://en.wikipedia.org/wiki/Fox", snippet: "Foxes are small to medium-sized, omnivorous mammals belonging to several genera of the family Canidae."},
    {title: "Dolphin - Wikipedia", url: "https://en.wikipedia.org/wiki/Dolphin", snippet: "A dolphin is an aquatic mammal within the infraorder Cetacea. Dolphins are highly intelligent marine mammals."},
    {title: "Whale - Wikipedia", url: "https://en.wikipedia.org/wiki/Whale", snippet: "Whales are a widely distributed and diverse group of fully aquatic placental marine mammals."},
    {title: "Penguin - Wikipedia", url: "https://en.wikipedia.org/wiki/Penguin", snippet: "Penguins are a group of aquatic flightless birds. They live almost exclusively in the Southern Hemisphere."},
    {title: "Eagle - Wikipedia", url: "https://en.wikipedia.org/wiki/Eagle", snippet: "Eagle is the common name for many large birds of prey of the family Accipitridae."},
    {title: "Owl - Wikipedia", url: "https://en.wikipedia.org/wiki/Owl", snippet: "Owls are birds from the order Strigiformes, which includes over 200 species of mostly solitary and nocturnal birds of prey."},
    {title: "Shark - Wikipedia", url: "https://en.wikipedia.org/wiki/Shark", snippet: "Sharks are a group of elasmobranch fish characterized by a cartilaginous skeleton, five to seven gill slits on the sides of the head."},
    {title: "Giraffe - Wikipedia", url: "https://en.wikipedia.org/wiki/Giraffe", snippet: "The giraffe is a large African hoofed mammal belonging to the genus Giraffa. It is the tallest living terrestrial animal."},
    {title: "Zebra - Wikipedia", url: "https://en.wikipedia.org/wiki/Zebra", snippet: "Zebras are African equines with distinctive black-and-white striped coats."},
    {title: "Monkey - Wikipedia", url: "https://en.wikipedia.org/wiki/Monkey", snippet: "Monkey is a common name that may refer to most mammals of the infraorder Simiiformes, also known as the simians."},
    {title: "Panda - Wikipedia", url: "https://en.wikipedia.org/wiki/Giant_panda", snippet: "The giant panda, also known as the panda bear, is a bear species endemic to China."},
    
    // Olympics Theme
    {title: "Olympic Games - Wikipedia", url: "https://en.wikipedia.org/wiki/Olympic_Games", snippet: "The modern Olympic Games are the leading international sporting events featuring summer and winter sports competitions."},
    {title: "Summer Olympic Games - Wikipedia", url: "https://en.wikipedia.org/wiki/Summer_Olympic_Games", snippet: "The Summer Olympic Games, also known as the Games of the Olympiad, are a major international multi-sport event."},
    {title: "Winter Olympic Games - Wikipedia", url: "https://en.wikipedia.org/wiki/Winter_Olympic_Games", snippet: "The Winter Olympic Games is a major international multi-sport event held once every four years for sports practiced on snow and ice."},
    {title: "Olympic Medals - Wikipedia", url: "https://en.wikipedia.org/wiki/Olympic_medal", snippet: "An Olympic medal is awarded to successful competitors at one of the Olympic Games."},
    {title: "Athletics - Wikipedia", url: "https://en.wikipedia.org/wiki/Sport_of_athletics", snippet: "Athletics is a group of sporting events that involves competitive running, jumping, throwing, and walking."},
    {title: "Swimming - Wikipedia", url: "https://en.wikipedia.org/wiki/Swimming_(sport)", snippet: "Swimming is an individual or team racing sport that requires the use of one's entire body to move through water."},
    {title: "Gymnastics - Wikipedia", url: "https://en.wikipedia.org/wiki/Gymnastics", snippet: "Gymnastics is a sport that includes physical exercises requiring balance, strength, flexibility, agility, coordination, and endurance."},
    {title: "Basketball - Wikipedia", url: "https://en.wikipedia.org/wiki/Basketball", snippet: "Basketball is a team sport in which two teams, most commonly of five players each, opposing one another on a rectangular court."},
    {title: "Soccer - Wikipedia", url: "https://en.wikipedia.org/wiki/Association_football", snippet: "Association football, more commonly known as football or soccer, is a team sport played between two teams of 11 players."},
    {title: "Tennis - Wikipedia", url: "https://en.wikipedia.org/wiki/Tennis", snippet: "Tennis is a racket sport that is played either individually against a single opponent or between two teams of two players each."},
    
    // Fruits Theme
    {title: "Apple - Wikipedia", url: "https://en.wikipedia.org/wiki/Apple", snippet: "An apple is an edible fruit produced by an apple tree. Apple trees are cultivated worldwide and are the most widely grown species in the genus Malus."},
    {title: "Banana - Wikipedia", url: "https://en.wikipedia.org/wiki/Banana", snippet: "A banana is an elongated, edible fruit – botanically a berry – produced by several kinds of large herbaceous flowering plants in the genus Musa."},
    {title: "Orange - Wikipedia", url: "https://en.wikipedia.org/wiki/Orange_(fruit)", snippet: "An orange is a fruit of various citrus species in the family Rutaceae; it primarily refers to Citrus × sinensis."},
    {title: "Strawberry - Wikipedia", url: "https://en.wikipedia.org/wiki/Strawberry", snippet: "The garden strawberry is a widely grown hybrid species of the genus Fragaria. It is cultivated worldwide for its fruit."},
    {title: "Grape - Wikipedia", url: "https://en.wikipedia.org/wiki/Grape", snippet: "A grape is a fruit, botanically a berry, of the deciduous woody vines of the flowering plant genus Vitis."},
    {title: "Watermelon - Wikipedia", url: "https://en.wikipedia.org/wiki/Watermelon", snippet: "Watermelon is a flowering plant species of the Cucurbitaceae family and the name of its edible fruit."},
    {title: "Mango - Wikipedia", url: "https://en.wikipedia.org/wiki/Mango", snippet: "A mango is an edible stone fruit produced by the tropical tree Mangifera indica."},
    {title: "Pineapple - Wikipedia", url: "https://en.wikipedia.org/wiki/Pineapple", snippet: "The pineapple is a tropical plant with an edible fruit; it is the most economically significant plant in the family Bromeliaceae."},
    {title: "Lemon - Wikipedia", url: "https://en.wikipedia.org/wiki/Lemon", snippet: "The lemon is a species of small evergreen tree in the flowering plant family Rutaceae, native to Asia."},
    {title: "Cherry - Wikipedia", url: "https://en.wikipedia.org/wiki/Cherry", snippet: "A cherry is the fruit of many plants of the genus Prunus, and is a fleshy drupe."},
    {title: "Peach - Wikipedia", url: "https://en.wikipedia.org/wiki/Peach", snippet: "The peach is a deciduous tree first domesticated and cultivated in Zhejiang province of Eastern China."},
    {title: "Pear - Wikipedia", url: "https://en.wikipedia.org/wiki/Pear", snippet: "Pears are fruits produced and consumed around the world, growing on a tree and harvested in late summer into mid-autumn."},
    
    // Countries Theme
    {title: "United States - Wikipedia", url: "https://en.wikipedia.org/wiki/United_States", snippet: "The United States of America, commonly known as the United States or America, is a country primarily located in North America."},
    {title: "Japan - Wikipedia", url: "https://en.wikipedia.org/wiki/Japan", snippet: "Japan is an island country in East Asia. It is situated in the northwest Pacific Ocean."},
    {title: "France - Wikipedia", url: "https://en.wikipedia.org/wiki/France", snippet: "France, officially the French Republic, is a country located primarily in Western Europe."},
    {title: "Germany - Wikipedia", url: "https://en.wikipedia.org/wiki/Germany", snippet: "Germany, officially the Federal Republic of Germany, is a country in Central Europe."},
    {title: "Brazil - Wikipedia", url: "https://en.wikipedia.org/wiki/Brazil", snippet: "Brazil, officially the Federative Republic of Brazil, is the largest country in South America and Latin America."},
    {title: "Canada - Wikipedia", url: "https://en.wikipedia.org/wiki/Canada", snippet: "Canada is a country in North America. Its ten provinces and three territories extend from the Atlantic Ocean to the Pacific Ocean."},
    {title: "Australia - Wikipedia", url: "https://en.wikipedia.org/wiki/Australia", snippet: "Australia, officially the Commonwealth of Australia, is a sovereign country comprising the mainland of the Australian continent."},
    {title: "Italy - Wikipedia", url: "https://en.wikipedia.org/wiki/Italy", snippet: "Italy, officially the Italian Republic, is a country consisting of a peninsula delimited by the Alps and several islands."},
    
    // Space Theme
    {title: "Mars - Wikipedia", url: "https://en.wikipedia.org/wiki/Mars", snippet: "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System."},
    {title: "Moon - Wikipedia", url: "https://en.wikipedia.org/wiki/Moon", snippet: "The Moon is Earth's only natural satellite. It is the fifth largest satellite in the Solar System."},
    {title: "Sun - Wikipedia", url: "https://en.wikipedia.org/wiki/Sun", snippet: "The Sun is the star at the center of the Solar System. It is a nearly perfect ball of hot plasma."},
    {title: "Jupiter - Wikipedia", url: "https://en.wikipedia.org/wiki/Jupiter", snippet: "Jupiter is the fifth planet from the Sun and the largest in the Solar System."},
    {title: "Saturn - Wikipedia", url: "https://en.wikipedia.org/wiki/Saturn", snippet: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter."},
    {title: "Black Hole - Wikipedia", url: "https://en.wikipedia.org/wiki/Black_hole", snippet: "A black hole is a region of spacetime where gravity is so strong that nothing, including light, can escape from it."},
    {title: "Galaxy - Wikipedia", url: "https://en.wikipedia.org/wiki/Galaxy", snippet: "A galaxy is a gravitationally bound system of stars, stellar remnants, interstellar gas, dust, and dark matter."},
    
    // Colors Theme
    {title: "Red - Wikipedia", url: "https://en.wikipedia.org/wiki/Red", snippet: "Red is the color at the long wavelength end of the visible spectrum of light."},
    {title: "Blue - Wikipedia", url: "https://en.wikipedia.org/wiki/Blue", snippet: "Blue is one of the three primary colours in the RYB colour model, as well as in the RGB colour model."},
    {title: "Green - Wikipedia", url: "https://en.wikipedia.org/wiki/Green", snippet: "Green is the color between cyan and yellow on the visible spectrum."},
    {title: "Yellow - Wikipedia", url: "https://en.wikipedia.org/wiki/Yellow", snippet: "Yellow is the color between green and orange on the spectrum of light."},
    {title: "Purple - Wikipedia", url: "https://en.wikipedia.org/wiki/Purple", snippet: "Purple is any of a variety of colors with hue between red and blue."},
    
    // Cool Game Websites
    {title: "Cool Math Games - Fun Online Games", url: "https://www.coolmathgames.com", snippet: "Cool Math Games is a brain-training site for everyone, where logic & thinking & math meets fun & games. Play free online games including puzzle games, strategy games, racing games and more!"},
    {title: "Miniclip - Free Online Games", url: "https://www.miniclip.com", snippet: "Play free online games including racing games, sports games, puzzle games, and more at Miniclip.com. 8 Ball Pool, Agar.io, and many more!"},
    {title: "Kongregate - Free Online Games", url: "https://www.kongregate.com", snippet: "Kongregate is a portal to thousands of free online games including strategy, action, arcade, and multiplayer games. Play now!"},
    {title: "Armor Games - Free Flash Games", url: "https://armorgames.com", snippet: "Armor Games offers a wide variety of award winning games and entertainment to millions of players online. Play free games on Armor Games!"},
    {title: "Addicting Games - Free Games", url: "https://www.addictinggames.com", snippet: "Play thousands of free online games including arcade games, puzzle games, funny games, sports games, action games, racing games and more!"},
    {title: "Newgrounds - Games, Movies, Art", url: "https://www.newgrounds.com", snippet: "Everything by Everyone. Newgrounds is a community of artists, game developers, musicians, and programmers creating content for everyone!"},
    {title: "Poki - Free Online Games", url: "https://poki.com", snippet: "Play the best free online games on Poki! We have thousands of games in all genres including action, puzzle, racing, and more."},
    {title: "Crazy Games - Free Games", url: "https://www.crazygames.com", snippet: "CrazyGames is a browser game platform that features the best free online games. All of our games run in the browser and can be played instantly."},
    {title: "Y8 Games - Free Games Online", url: "https://www.y8.com", snippet: "Play millions of free games on your smartphone, tablet, computer, Xbox One, Oculus Rift, and more at Y8.com."},
    {title: "Kizi - Free Online Games", url: "https://www.kizi.com", snippet: "Kizi offers a selection of the best games on the web, including exclusive Kizi games. Play now for free!"},
    {title: "Friv - Free Online Games", url: "https://www.friv.com", snippet: "Friv Games offers the largest collection of free online games. Play racing games, sports games, shooting games, and much more on Friv!"},
    {title: "Agame - Free Online Games", url: "https://www.agame.com", snippet: "Play the best free online games on Agame.com! Enjoy games like racing, shooting, sports, and more!"},
    {title: "Nitrome - Free Flash Games", url: "https://www.nitrome.com", snippet: "Nitrome creates unique platform, puzzle, and other cool games for web and mobile. Play our games now!"},
    {title: "Papa's Games - Cooking Games", url: "https://www.coolmathgames.com/0-papas-games", snippet: "Papa's games are strategy and management games where you run a restaurant. Cook food, take orders, and serve customers in Papa's Pizzeria, Freezeria, and more!"},
    {title: "Run 3 - Cool Math Games", url: "https://www.coolmathgames.com/0-run-3", snippet: "Run 3 is an endless running game where you need to navigate through space tunnels. Jump from platform to platform and don't fall into the abyss!"},
    {title: "Fireboy and Watergirl - Games", url: "https://www.coolmathgames.com/0-fireboy-and-watergirl-the-forest-temple", snippet: "Fireboy and Watergirl is a puzzle platformer where you control two characters and solve puzzles together. Work as a team to beat all levels!"},
    {title: "Bloons Tower Defense - Strategy", url: "https://www.coolmathgames.com/0-bloons-tower-defense", snippet: "Bloons Tower Defense is a strategy game where you defend your territory from invading balloons by placing monkey towers."},
    {title: "Chess - Cool Math Games", url: "https://www.coolmathgames.com/0-chess", snippet: "Play chess online for free! Challenge the computer or play against friends. Improve your chess skills with this classic strategy game."},
    {title: "Snake - Classic Game", url: "https://www.google.com/fbx?fbx=snake_arcade", snippet: "Snake is a classic arcade game where you control a growing snake. Eat the food to grow longer but don't run into yourself!"},
    {title: "Tetris - Classic Puzzle Game", url: "https://tetris.com/play-tetris", snippet: "Play the official Tetris game online! Arrange falling blocks to clear lines in this timeless puzzle game."},
    
    // Teacher Organization & Education Apps
    {title: "Google Classroom - Teaching Platform", url: "https://classroom.google.com", snippet: "Google Classroom is a free web service developed by Google for schools that aims to simplify creating, distributing, and grading assignments."},
    {title: "Kahoot! - Learning Games", url: "https://kahoot.com", snippet: "Kahoot! is a game-based learning platform used as educational technology in schools and other educational institutions."},
    {title: "Quizizz - Interactive Quizzes", url: "https://quizizz.com", snippet: "Quizizz is an interactive learning platform used by teachers to create fun multiplayer activities for students."},
    {title: "Edmodo - Education Network", url: "https://www.edmodo.com", snippet: "Edmodo is an educational technology company offering communication, collaboration, and coaching platform to K-12 schools and teachers."},
    {title: "Canvas LMS - Learning Management", url: "https://www.instructure.com/canvas", snippet: "Canvas is a modern, open-source learning management system developed and maintained by Instructure Inc."},
    {title: "Schoology - Learning Platform", url: "https://www.schoology.com", snippet: "Schoology is a virtual learning environment and social networking service for K-12 schools and higher education institutions."},
    {title: "Seesaw - Student Portfolio", url: "https://web.seesaw.me", snippet: "Seesaw is a student-driven digital portfolio that empowers students to document what they are learning at school."},
    {title: "Nearpod - Interactive Lessons", url: "https://nearpod.com", snippet: "Nearpod is a platform that combines interactive lessons, videos, and activities to create an engaging learning experience."},
    {title: "Remind - Communication App", url: "https://www.remind.com", snippet: "Remind is a communication platform that helps teachers reach students and parents where they are - messaging app for education."},
    {title: "ClassDojo - Classroom Management", url: "https://www.classdojo.com", snippet: "ClassDojo connects teachers with students and parents to build amazing classroom communities."},
    {title: "Gradebook - Grade Tracking", url: "https://www.teacherease.com", snippet: "Digital gradebook and student information system for teachers to track student progress and grades."},
    {title: "Planbook - Lesson Planning", url: "https://www.planbook.com", snippet: "Planbook is a lesson planning application designed to make teachers' lives easier by simplifying the planning process."},
    {title: "TeacherPay Teachers - Resources", url: "https://www.teacherspayteachers.com", snippet: "Teachers Pay Teachers is an online marketplace for buying and selling original educational materials created by teachers."},
    {title: "BrainPOP - Educational Videos", url: "https://www.brainpop.com", snippet: "BrainPOP creates animated, curriculum-based content that supports educators and engages students."},
    
    // More Popular Websites & Services
    {title: "Etsy - Handmade Marketplace", url: "https://www.etsy.com", snippet: "Etsy is an e-commerce website focused on handmade or vintage items and craft supplies."},
    {title: "Shopify - E-commerce Platform", url: "https://www.shopify.com", snippet: "Shopify is a commerce platform that allows anyone to set up an online store and sell their products."},
    {title: "Square - Payment Processing", url: "https://squareup.com", snippet: "Square is a financial services, merchant services aggregator, and mobile payment company."},
    {title: "Stripe - Online Payments", url: "https://stripe.com", snippet: "Stripe is a technology company that builds economic infrastructure for the internet. Payment processing for internet businesses."},
    {title: "WordPress - Website Builder", url: "https://wordpress.com", snippet: "WordPress.com is a free website builder and blogging platform. Create a beautiful website easily."},
    {title: "Wix - Website Creator", url: "https://www.wix.com", snippet: "Wix is a cloud-based web development platform that allows users to create HTML5 websites through drag-and-drop tools."},
    {title: "Squarespace - Website Platform", url: "https://www.squarespace.com", snippet: "Squarespace is an all-in-one platform to build a beautiful website, online store, or portfolio."},
    {title: "GoDaddy - Domain Registration", url: "https://www.godaddy.com", snippet: "GoDaddy is a web hosting and domain registration company. Get your domain name today!"},
    {title: "Namecheap - Domain Names", url: "https://www.namecheap.com", snippet: "Namecheap offers cheap domain names, web hosting, SSL certificates, and more at affordable prices."},
    {title: "Bluehost - Web Hosting", url: "https://www.bluehost.com", snippet: "Bluehost is one of the largest website hosting providers and powers millions of websites worldwide."},
    {title: "HostGator - Hosting Services", url: "https://www.hostgator.com", snippet: "HostGator provides shared, reseller, VPS and dedicated web hosting. Reliable web hosting made affordable."},
    {title: "CloudFlare - CDN Services", url: "https://www.cloudflare.com", snippet: "Cloudflare is a web infrastructure and website security company that provides content delivery network services."},
    {title: "Heroku - Cloud Platform", url: "https://www.heroku.com", snippet: "Heroku is a cloud platform as a service supporting several programming languages for web application deployment."},
    {title: "DigitalOcean - Cloud Hosting", url: "https://www.digitalocean.com", snippet: "DigitalOcean provides developers cloud services to deploy, manage, and scale applications."},
    {title: "AWS - Amazon Web Services", url: "https://aws.amazon.com", snippet: "Amazon Web Services offers reliable, scalable, and inexpensive cloud computing services."},
    {title: "Azure - Microsoft Cloud", url: "https://azure.microsoft.com", snippet: "Microsoft Azure is a cloud computing service for building, testing, deploying, and managing applications."},
    {title: "Firebase - App Development", url: "https://firebase.google.com", snippet: "Firebase is Google's mobile platform that helps you quickly develop high-quality apps."},
    {title: "MongoDB - Database Platform", url: "https://www.mongodb.com", snippet: "MongoDB is a general purpose, document-based, distributed database built for modern application developers."},
    {title: "PostgreSQL - Database", url: "https://www.postgresql.org", snippet: "PostgreSQL is a powerful, open source object-relational database system."},
    {title: "MySQL - Database System", url: "https://www.mysql.com", snippet: "MySQL is the world's most popular open source database used by major companies."},
    {title: "Redis - Data Structure Store", url: "https://redis.io", snippet: "Redis is an open source, in-memory data structure store, used as a database, cache, and message broker."},
    {title: "Docker - Container Platform", url: "https://www.docker.com", snippet: "Docker is a platform designed to help developers build, share, and run modern applications."},
    {title: "Kubernetes - Container Orchestration", url: "https://kubernetes.io", snippet: "Kubernetes is an open-source system for automating deployment, scaling, and management of containerized applications."},
    {title: "Jenkins - Automation Server", url: "https://www.jenkins.io", snippet: "Jenkins is an open source automation server used to automate all sorts of tasks related to building and testing software."},
    {title: "Jira - Project Management", url: "https://www.atlassian.com/software/jira", snippet: "Jira is a proprietary issue tracking product developed by Atlassian for agile project management."},
    {title: "Confluence - Team Workspace", url: "https://www.atlassian.com/software/confluence", snippet: "Confluence is a collaboration software program designed to help teams collaborate and share knowledge efficiently."},
    {title: "Monday.com - Work OS", url: "https://monday.com", snippet: "Monday.com is a Work OS that powers teams to run processes, projects and workflows in one digital workspace."},
    {title: "ClickUp - Productivity Platform", url: "https://clickup.com", snippet: "ClickUp is a productivity platform that makes it easy to manage people, projects, and priorities."},
    {title: "Airtable - Collaboration Platform", url: "https://www.airtable.com", snippet: "Airtable is a cloud collaboration service that combines features of a database with a spreadsheet."},
    {title: "Basecamp - Project Management", url: "https://basecamp.com", snippet: "Basecamp is a real-time communication tool that helps teams stay on the same page."},
    {title: "Smartsheet - Work Management", url: "https://www.smartsheet.com", snippet: "Smartsheet is a software as a service offering for collaboration and work management."},
    {title: "Box - Cloud Storage", url: "https://www.box.com", snippet: "Box is a cloud content management and file sharing service for businesses."},
    {title: "WeTransfer - File Transfer", url: "https://wetransfer.com", snippet: "WeTransfer is a cloud-based computer file transfer service used to send large files."},
    {title: "SendGrid - Email Delivery", url: "https://sendgrid.com", snippet: "SendGrid provides a cloud-based email delivery platform for transactional and marketing emails."},
    {title: "Mailchimp - Email Marketing", url: "https://mailchimp.com", snippet: "Mailchimp is an all-in-one marketing platform that helps small businesses grow."},
    {title: "HubSpot - CRM Platform", url: "https://www.hubspot.com", snippet: "HubSpot offers a full platform of marketing, sales, customer service, and CRM software."},
    {title: "Salesforce - CRM Solution", url: "https://www.salesforce.com", snippet: "Salesforce is the world's #1 CRM platform that brings companies and customers together."},
    {title: "Zapier - Automation Tool", url: "https://zapier.com", snippet: "Zapier is an automation tool that connects your apps and services to create automated workflows."},
    {title: "IFTTT - Automation Service", url: "https://ifttt.com", snippet: "IFTTT helps connect different apps and devices. When this happens, do that."},
    {title: "Buffer - Social Media Manager", url: "https://buffer.com", snippet: "Buffer is a social media management platform that helps you schedule posts and analyze results."},
    {title: "Hootsuite - Social Media Tool", url: "https://hootsuite.com", snippet: "Hootsuite is a social media management platform that covers almost every aspect of social media marketing."},
    {title: "Canva Pro - Design Platform", url: "https://www.canva.com/pro", snippet: "Canva Pro gives you access to premium templates, photos, and features for professional design."},
    {title: "Grammarly - Writing Assistant", url: "https://www.grammarly.com", snippet: "Grammarly is a writing assistant that helps you compose clear, mistake-free writing."},
    {title: "Hemingway Editor - Writing Tool", url: "https://hemingwayapp.com", snippet: "Hemingway App makes your writing bold and clear by highlighting common errors."},
    {title: "Evernote - Note Taking", url: "https://evernote.com", snippet: "Evernote helps you capture and prioritize ideas, projects, and to-do lists."},
    {title: "OneNote - Digital Notebook", url: "https://www.onenote.com", snippet: "Microsoft OneNote is a digital notebook that provides a place for all of your notes and information."},
    {title: "Todoist - Task Manager", url: "https://todoist.com", snippet: "Todoist is a to-do list and task manager that helps you organize your work and life."},
    {title: "Any.do - To-Do List", url: "https://www.any.do", snippet: "Any.do is a to-do list, calendar, and reminders app designed to help you stay organized."},
    {title: "Habitica - Gamified Tasks", url: "https://habitica.com", snippet: "Habitica is a free habit and productivity app that treats your real life like a game."},
    {title: "Forest - Focus App", url: "https://www.forestapp.cc", snippet: "Forest is an app that helps you stay focused on your work by planting virtual trees."},
    {title: "Pomodoro Timer - Time Management", url: "https://pomofocus.io", snippet: "Pomodoro Timer is a time management method that uses a timer to break work into intervals."},
    {title: "RescueTime - Time Tracker", url: "https://www.rescuetime.com", snippet: "RescueTime is a time management and productivity tool that helps you understand your daily habits."},
    {title: "Toggl - Time Tracking", url: "https://toggl.com", snippet: "Toggl is a time tracking app that helps you track your work hours and improve productivity."},
    {title: "Clockify - Free Time Tracker", url: "https://clockify.me", snippet: "Clockify is a free time tracker and timesheet app that lets you track work hours."},
    {title: "Calendly - Scheduling Tool", url: "https://calendly.com", snippet: "Calendly is a scheduling automation platform for eliminating the back-and-forth emails."},
    {title: "Doodle - Meeting Scheduler", url: "https://doodle.com", snippet: "Doodle is the simplest way to schedule meetings with clients, colleagues, or friends."},
    {title: "Miro - Online Whiteboard", url: "https://miro.com", snippet: "Miro is the online collaborative whiteboard platform to bring teams together, anytime, anywhere."},
    {title: "Lucidchart - Diagramming", url: "https://www.lucidchart.com", snippet: "Lucidchart is an intelligent diagramming application that brings teams together."},
    {title: "Draw.io - Diagram Software", url: "https://app.diagrams.net", snippet: "Draw.io is free online diagram software for making flowcharts, process diagrams, and more."},
    {title: "Prezi - Presentation Software", url: "https://prezi.com", snippet: "Prezi is a presentation software that uses motion, zoom, and spatial relationships."},
    {title: "Slides - Presentation Maker", url: "https://slides.com", snippet: "Slides is a place for creating, presenting and sharing slide decks online."},
    {title: "Loom - Video Messaging", url: "https://www.loom.com", snippet: "Loom is a video messaging tool that helps you get your message across through instantly shareable videos."},
    {title: "OBS Studio - Broadcasting", url: "https://obsproject.com", snippet: "OBS Studio is free and open source software for video recording and live streaming."},
    {title: "StreamYard - Live Streaming", url: "https://streamyard.com", snippet: "StreamYard is a live streaming studio in your browser for easy professional broadcasts."},
    {title: "Restream - Multi-streaming", url: "https://restream.io", snippet: "Restream helps you stream live video to multiple platforms simultaneously."},
    {title: "Audacity - Audio Editor", url: "https://www.audacityteam.org", snippet: "Audacity is a free, easy-to-use, multi-track audio editor and recorder."},
    {title: "GIMP - Image Editor", url: "https://www.gimp.org", snippet: "GIMP is a free and open-source image editor used for image manipulation and editing."},
    {title: "Inkscape - Vector Graphics", url: "https://inkscape.org", snippet: "Inkscape is a free and open-source vector graphics editor used to create vector images."},
    {title: "Blender - 3D Creation", url: "https://www.blender.org", snippet: "Blender is the free and open source 3D creation suite supporting modeling, animation, and rendering."},
    {title: "Unity - Game Engine", url: "https://unity.com", snippet: "Unity is a cross-platform game engine used to develop video games for PC, consoles, mobile and websites."},
    {title: "Unreal Engine - Game Development", url: "https://www.unrealengine.com", snippet: "Unreal Engine is a game engine developed by Epic Games for creating high-quality games."},
    {title: "Godot - Open Source Engine", url: "https://godotengine.org", snippet: "Godot is a free and open-source game engine that provides a feature-packed platform for game development."},
    {title: "Visual Studio Code - Code Editor", url: "https://code.visualstudio.com", snippet: "Visual Studio Code is a source-code editor made by Microsoft for Windows, Linux and macOS."},
    {title: "Sublime Text - Text Editor", url: "https://www.sublimetext.com", snippet: "Sublime Text is a sophisticated text editor for code, markup and prose."},
    {title: "Atom - Hackable Editor", url: "https://atom.io", snippet: "Atom is a free and open-source text and source code editor developed by GitHub."},
    {title: "Notepad++ - Code Editor", url: "https://notepad-plus-plus.org", snippet: "Notepad++ is a free source code editor and Notepad replacement that supports several languages."},
    {title: "Replit - Online IDE", url: "https://replit.com", snippet: "Replit is a browser-based IDE that lets you code in any language without setup."},
    {title: "CodeSandbox - Online Editor", url: "https://codesandbox.io", snippet: "CodeSandbox is an online code editor and prototyping tool for rapid web development."},
    {title: "Glitch - Build Apps", url: "https://glitch.com", snippet: "Glitch is a collaborative programming environment that lets you build web apps instantly."},
    {title: "Postman - API Platform", url: "https://www.postman.com", snippet: "Postman is an API platform for building and using APIs. Simplify API development."},
    {title: "Insomnia - API Client", url: "https://insomnia.rest", snippet: "Insomnia is a collaborative open source API client that makes REST and GraphQL easy."},
    {title: "Swagger - API Documentation", url: "https://swagger.io", snippet: "Swagger is a suite of tools for API developers from SmartBear Software."},
    
    // OvO and More Games
    {title: "OvO - Parkour Game", url: "https://www.coolmathgames.com/0-ovo", snippet: "OvO is a fast-paced parkour platformer game. Use precise movements to navigate through challenging levels and reach the flag!"},
    {title: "OvO 2 - Sequel Game", url: "https://www.coolmathgames.com/0-ovo-2", snippet: "OvO 2 is the sequel to the popular parkour game with new levels, mechanics, and challenges. Master the controls and speedrun!"},
    {title: "Vex Series - Stickman Parkour", url: "https://www.coolmathgames.com/0-vex-7", snippet: "Vex is a challenging stickman parkour game series. Run, jump, slide, and climb through deadly obstacle courses!"},
    {title: "Getting Over It - Climbing Game", url: "https://www.coolmathgames.com/0-getting-over-it", snippet: "Getting Over It is a punishing climbing game where you control a man in a pot with a hammer. Don't fall!"},
    
    // K-8 Educational Broadcast & Teacher Resources
    {title: "PBS LearningMedia - K-12 Resources", url: "https://www.pbslearningmedia.org", snippet: "PBS LearningMedia offers free educational videos, lessons, and activities for K-12 teachers and students."},
    {title: "Discovery Education - K-12 Content", url: "https://www.discoveryeducation.com", snippet: "Discovery Education provides K-12 digital curriculum resources, professional development, and student engagement solutions."},
    {title: "Scholastic - Teacher Resources", url: "https://www.scholastic.com/teachers", snippet: "Scholastic Teachers offers free lesson plans, classroom resources, book recommendations, and educational activities for K-8."},
    {title: "National Geographic Education", url: "https://education.nationalgeographic.org", snippet: "National Geographic Education provides K-12 resources including maps, activities, and lesson plans on geography, science, and culture."},
    {title: "Edutopia - Teaching Strategies", url: "https://www.edutopia.org", snippet: "Edutopia is a comprehensive resource for K-12 educators featuring evidence-based teaching strategies and classroom practices."},
    {title: "ReadWriteThink - Literacy Resources", url: "https://www.readwritethink.org", snippet: "ReadWriteThink provides K-12 literacy lesson plans, student interactives, and professional development resources for teachers."},
    {title: "Math Playground - K-8 Math Games", url: "https://www.mathplayground.com", snippet: "Math Playground features math games, logic puzzles, and problem solving activities for K-8 students."},
    {title: "Prodigy Math - K-8 Math Platform", url: "https://www.prodigygame.com", snippet: "Prodigy is a curriculum-aligned math game for grades 1-8 that makes learning fun through game-based activities."},
    {title: "IXL Learning - K-12 Practice", url: "https://www.ixl.com", snippet: "IXL offers comprehensive K-12 practice in math, language arts, science, and social studies with personalized learning."},
    {title: "ABCya - Elementary Games", url: "https://www.abcya.com", snippet: "ABCya provides educational games and activities for K-5 students covering math, reading, typing, and more."},
    {title: "Starfall - K-3 Reading", url: "https://www.starfall.com", snippet: "Starfall is a free public service to teach children to read with phonics for kindergarten through third grade."},
    {title: "Funbrain - K-8 Games", url: "https://www.funbrain.com", snippet: "Funbrain offers free educational games, videos, and books for K-8 students covering math, reading, and problem-solving."},
    {title: "PBS Kids - Educational Videos", url: "https://pbskids.org", snippet: "PBS Kids offers educational games, videos, and activities featuring beloved characters to help children learn."},
    {title: "Sesame Street - Early Learning", url: "https://www.sesamestreet.org", snippet: "Sesame Street provides educational content for preschool and early elementary students with videos, games, and activities."},
    {title: "Reading Rockets - Literacy", url: "https://www.readingrockets.org", snippet: "Reading Rockets offers research-based reading strategies, lessons, and activities for K-3 teachers and parents."},
    {title: "CommonLit - Reading Lessons", url: "https://www.commonlit.org", snippet: "CommonLit is a free collection of reading passages and literacy resources for grades 3-12 teachers."},
    {title: "TeachEngineering - STEM Lessons", url: "https://www.teachengineering.org", snippet: "TeachEngineering provides K-12 STEM curriculum featuring hands-on, real-world engineering activities and lessons."},
    {title: "Mystery Science - Science Lessons", url: "https://mysteryscience.com", snippet: "Mystery Science offers K-5 science lessons that inspire kids to love science through engaging mysteries and hands-on activities."},
    {title: "Generation Genius - Science Videos", url: "https://www.generationgenius.com", snippet: "Generation Genius provides K-8 science videos and lessons aligned with NGSS standards for elementary and middle school."},
    {title: "Crash Course Kids - Science", url: "https://thecrashcourse.com/courses/crashcoursekids", snippet: "Crash Course Kids offers free educational science videos for upper elementary and middle school students."},
    {title: "SciShow Kids - Science Videos", url: "https://www.youtube.com/scishowkids", snippet: "SciShow Kids features fun science videos exploring nature, space, technology, and more for young learners."},
    {title: "Code.org - Computer Science", url: "https://code.org", snippet: "Code.org teaches K-12 students computer science fundamentals through free online courses and activities."},
    {title: "Scratch - Visual Programming", url: "https://scratch.mit.edu", snippet: "Scratch is a free programming language for kids ages 8+ to create interactive stories, games, and animations."},
    {title: "Tynker - Coding for Kids", url: "https://www.tynker.com", snippet: "Tynker teaches kids programming through game-based courses and creative coding projects for K-8."},
    {title: "Education.com - Worksheets", url: "https://www.education.com", snippet: "Education.com offers printable worksheets, lesson plans, and learning games for Pre-K through 5th grade."},
    {title: "Teachers Pay Teachers Premium", url: "https://www.teacherspayteachers.com/Browse", snippet: "Browse thousands of teacher-created resources, lesson plans, activities, and worksheets for all grades and subjects."},
    {title: "We Are Teachers - Community", url: "https://www.weareteachers.com", snippet: "We Are Teachers is an online community providing teaching tips, classroom ideas, and educational resources for K-12 teachers."},
    {title: "Teach Starter - Resources", url: "https://www.teachstarter.com", snippet: "Teach Starter offers time-saving teaching resources, worksheets, activities, and lesson plans for K-6 teachers."},
    {title: "Flocabulary - Educational Hip-Hop", url: "https://www.flocabulary.com", snippet: "Flocabulary uses educational hip-hop music and videos to teach K-12 curriculum across all subjects."},
    {title: "BoomWriter - Creative Writing", url: "https://boomwriter.com", snippet: "BoomWriter is a collaborative writing platform for K-8 students to develop creative writing skills."},
    {title: "Typing Club - Typing Lessons", url: "https://www.typingclub.com", snippet: "Typing Club offers free touch typing lessons and games for K-12 students to improve keyboarding skills."},
    
    // OrangeVale K-8 & Additional Education Sites
    {title: "OrangeVale K-8 - Roseville School", url: "https://www.rjuhsd.us/orangevale", snippet: "OrangeVale K-8 School in Roseville - Home of the Bobcats! A quality education for students in Kindergarten through 8th grade."},
    {title: "Bobcat Broadcast - OrangeVale K-8", url: "https://www.youtube.com/@orangevalek8", snippet: "Watch the latest Bobcat Broadcast episodes featuring OrangeVale K-8 school news, student projects, and community updates!"},
    {title: "Blooket - Game-Based Learning", url: "https://www.blooket.com", snippet: "Blooket is a game-based learning platform where students answer questions to compete in exciting game modes. Perfect for K-8 classrooms!"},
    {title: "Gimkit - Live Learning Game", url: "https://www.gimkit.com", snippet: "Gimkit is a live learning game show platform where students earn virtual currency by answering questions correctly. Engaging K-8 review tool!"},
];
